# Generated by Django 4.0.6 on 2022-07-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва глави')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('text', models.TextField(verbose_name='Текст глави')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Час створення')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Час зміни')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
            ],
            options={
                'verbose_name': 'Глава',
                'verbose_name_plural': 'Глави',
                'ordering': ['id', 'title', 'time_create'],
            },
        ),
    ]
